import 'narration.g.dart';

/// One spoken line of the showcase, placed on its timeline by `tool/narrate.py`.
class NarrationLine {
  const NarrationLine({required this.chapter, required this.text, required this.start, required this.duration, required this.words});

  final String chapter;
  final String text;

  /// Seconds into the showcase when the line starts, and how long it runs.
  final double start;
  final double duration;

  /// Each word as written in the script, timed from what Whisper heard.
  final List<NarrationWord> words;

  double get end => start + duration;
}

/// A word of a line and when it is spoken.
class NarrationWord {
  const NarrationWord(this.word, this.start, this.end);

  final String word;
  final double start;
  final double end;
}

/// One video's narration: its timed lines and when its voiceover ends. The phone tour and the
/// wide-format video each have one, generated by `tool/narrate.py`.
class NarrationScript {
  const NarrationScript(this.lines, this.end);

  final List<NarrationLine> lines;

  /// When the voiceover ends, tail included.
  final double end;

  List<NarrationLine> of(final String chapter) => lines.where((final NarrationLine line) => line.chapter == chapter).toList();

  /// The chapters in the order they play.
  List<String> get chapters {
    final List<String> keys = <String>[];
    for (final NarrationLine line in lines) {
      if (!keys.contains(line.chapter)) {
        keys.add(line.chapter);
      }
    }
    return keys;
  }

  /// When [word] is first spoken in [chapter], or null if it never is.
  double? when(final String chapter, final String word) {
    for (final NarrationLine line in of(chapter)) {
      for (final NarrationWord spoken in line.words) {
        if (spoken.word == word) {
          return spoken.start;
        }
      }
    }
    return null;
  }

  /// The line on screen at [t] in [chapter]: the latest that has started, or before the first
  /// line, that first line. Empty for a chapter with no lines.
  String lineAt(final String chapter, final double t) {
    final List<NarrationLine> lines = of(chapter);
    if (lines.isEmpty) {
      return '';
    }
    NarrationLine shown = lines.first;
    for (final NarrationLine line in lines) {
      if (line.start <= t) {
        shown = line;
      }
    }
    return shown.text;
  }
}

/// The phone tour's narration, read by its timeline.
abstract final class Narration {
  static const NarrationScript script = NarrationScript(narrationLines, narrationEnd);

  static List<NarrationLine> get lines => script.lines;

  static double get end => script.end;

  static List<NarrationLine> of(final String chapter) => script.of(chapter);

  /// When [word] is first spoken in [chapter], or null if it never is.
  static double? when(final String chapter, final String word) => script.when(chapter, word);
}
